services:
  postgres:
    image: postgres:15-alpine
    container_name: iron-ledger-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: ironledger
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine
    container_name: iron-ledger-redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  pgdata: